Rakefile
=> Add descriptions of group rake tasks

Gemfile
fixed rack version temporarily to work with ruby 2.2.4
=> Gemfile Updates

Jenkinsfile
Updating CI workflow to support ruby 2.2.4 and bundler 1.x.
=> update Jenkinsfile to support ruby 2.2.4 and bundler 1.x

Gemfile, example_project.json, mappers/Baseline.rb
=> Mapping Site Properties into features

example_project.json, mappers/Baseline.rb
check dates in geojson and make sure they are in correct format for OSW.
=> check date format, convert from UI timestamp

example_project.json, mappers/Baseline.rb
This closes urbanopt/urbanopt-cli#26
=> Mapping for start time and duration

mappers/Baseline.rb, mappers/base_workflow.osw
=> Skips change building location measure when detailed model present

Gemfile, mappers/Baseline.rb
=> Modify baseline mapper for ChangeBuildingLocation

mappers/Baseline.rb, mappers/base_workflow.osw
=> adding vintage and template mappings for DEER

example_project.json, mappers/Baseline.rb
Correctly replace timesteps_per_hour, begin_date, and end_date in the template OSW.
=> fix for #52 set set_run_period arguments correctly

Gemfile, mappers/Baseline.rb, mappers/base_workflow.osw
add feature_location argument to reporting measure and assign it in the mapper class
=> add feature_location

Jenkinsfile
Updating the Jenkinsfile to use a new CI workflow.  
See https://github.com/NREL/cbci_jenkins_libs/blob/develop/vars/urbanopt_example_geojson_project.groovy for full workflow.
=> Updating CI workflow

.gitignore, Gemfile, README.md, Rakefile, example_project.json
Organize json file to be easier to read by humans. If I did it right, no data was added or removed.
=> Json organizing

LICENSE.md, README.md, Rakefile, example_project/mappers/Baseline.rb, example_project/mappers/HighEfficiency.rb, example_project/mappers/ThermalStorage.rb
Addresses #74: adding TM symbol to files
=> adding tm to files

Rakefile, example_project/mappers/CreateBar.rb, example_project/mappers/Floorspace.rb, example_project/mappers/createbar_workflow.osw
=> Adds create bar to mapper arguments, edits rakefile arguments

README.md
=> Adds instructions for rake tasks to Readme

Gemfile, Rakefile, example_project/visualization/input_visualization_feature.html, example_project/visualization/input_visualization_scenario.html
pulling in gemfile and other updates
=> gem updates and visualize functionality update to match CLI

example_project/mappers/Baseline.rb
Update the mapping of Laboratory model to the new developed Laboratory prototype for ASHRAE 90.1
=> Utilize ASHRAE 90.1 Laboratory prototype model

example_project/mappers/CreateBar.rb
=> Edit create bar mapper

example_project/mappers/CreateBar.rb, example_project/mappers/createbar_workflow.osw
Adding generic_qaqc measure to createbar workflow. Also added envelope and internal load reporting measure. A number of fixes to QAQC measure are on PR for common measures. There are more checks too add to the measure.
https://github.com/NREL/openstudio-common-measures-gem/pull/93
Once this is in we can can crate consolidated reporting of QAQC flags, but should probably wait until more testing is done, after the release.
=> Qaqc measure

.github/workflows/nightly_build.yml, Gemfile, README.md, Rakefile
Really resolves #159 for realzies this time.
The new action ran on schedule as expected but failed because there were a number of details that weren't correct. This PR fixes the problems.
BIG thank you to @tijcolem for advice on this PR, including how to test CI before merging and other remedial instruction.
You can see in the previous commit that the nightly-build check ran successfully.
- Use OS3.4.0 container to get Ruby (and OpenStudio)
- Add env vars that actually work
- Keep certificate bundle updated
=> Fix the Github Action so it does what I expect

example_project/mappers/Baseline.rb
=> fix non-integer feature ID for BuildResidentialModel

.github/workflows/nightly_build.yml, .gitignore, Gemfile, Rakefile, spec/example_project_spec.rb, spec/spec_helper.rb
Resolves #160 Resolves #156 
- Set up rspec tests
- Enable Coveralls Github action to track test coverage
=> developing rspec tests

example_project/mappers/base_workflow.osw
=> add modelica measures for gmt workflow

Gemfile
=> updating load-flex measure gem version

example_project/baseline_scenario.csv, example_project/example_project_combined.json, example_project/mappers/Baseline.rb, example_project/mappers/residential/samples/util.rb, example_project/measures/BuildResidentialModel/measure.rb, example_project/measures/BuildResidentialModel/tests/test_build_residential_model.rb
Refactor new `Baseline.rb` methods into separate `util.rb` file so that we can run unit tests on them.
=> Residential: connect to ResStock, follow-up
